dataloaders: 
  evaluate:
    dataset: /nas/slam/datasets/GAPR/dataset/1210-1138/evaluate
    collate: 
      name: MetricCollate
    augment:
      name: EvaluateAugment 
      rotate_cmd: zxy10
      translate_delta: 0.0
      if_jrr: no
    sampler:
      name: BatchSample
      batch_size: 1
      batch_size_limit: null
      batch_expansion_rate: null
      # sample kw
      shuffle: false
      max_batches: null
    num_workers: 1

