dataloaders: 
  # phase train
  train:
    dataset: /nas/slam/datasets/GAPR/dataset/benchmark/train
    collate: 
      name: MetricCollate
    augment:
      name: TrainAugment 
      rotate_cmd: zxy10 
      translate_delta: 1.0
      if_jrr: no
    sampler:
      name: HeteroTripletSample
      batch_size: 16
      batch_size_limit: 32
      batch_expansion_rate: 1.4
      max_batches: null
    num_workers: 4

method:
  model: 
    name: GAPR
    debug: no
    minkfpn:
      quant_size: 0.6
      in_channels: 1
      out_channels: 256
      num_top_down: 1
      conv0_kernel_size: 5
      layers: [1, 1, 1] 
      planes: [32, 64, 64]
    pctrans:
      dim: 256
      num_heads: 2
      mlp_ratio: 4
      depth: 1
      qkv_bias: yes
      init_values: null
      drop: 0.0
      attn_drop: 0.0
      drop_path_rate: 0.0
    meangem:
      p: 3.0 
      eps: 0.000001
  loss: 
    name: GAPRLoss
    # 20230513_095929, batch hard 1.0, point hard  2.7: 0.990 0.941 0.962 0.991
    # 20230513_103903, batch hard 1.0, point soft 10.0: 0.994 0.947 0.964 0.993 ✅
    # 20230513_112419, batch hard 1.0, point hard 10.0: 0.991 0.943 0.955 0.989
    # 20230513_120323, batch soft 1.0, point hard 10.0: 0.988 0.938 0.945 0.986
    # 20230513_131227, batch soft 1.0, point soft 10.0: 0.988 0.944 0.951 0.987
    batch_loss:
      margin: 1.0
      style: hard
    point_loss:
      margin: 10.0
      style: soft
      corr_dist: 2.0
      sample_num: 64
      pos_dist: 2.1 
      neg_dist: 20.0
    overlap_loss:
      corr_dist: 2.0
    # 0.5 > 1.0
    point_loss_scale: 0.5
    # 1.0 > 0.1, 1.0 > 1.5
    overlap_loss_scale: 1.0

train:
  lr: 0.001
  epochs: 40
  weight_decay: 0.001
  batch_expansion_th: 0.7
  scheduler_milestones: [15, 30]

dist:
  backend: nccl
  find_unused_parameters: no

results:
  weights: results/weights
  logs:    null # no used
